name: file_storage

networks:
  net-gateway:
    name: file_storage_gateway
    driver: bridge
  net-pg:
    name: file_storage_pg
    driver: bridge

volumes:
  pg-data:
    name: file_storage_pg-data
  media:
    name: file_storage_media

services:
  gateway:
    container_name: file_storage_gateway
    build:
      context: .
      dockerfile: ./dockerization/dockerfile.gateway
      args:
        NGINX_VERSION: 1.27.1
    volumes:
      - media:/var/www/media
    ports:
      - ${GATEWAY_HOST}:${GATEWAY_PORT}:80
    networks:
      - net-gateway
    depends_on:
      - api

  api:
    container_name: file_storage_api
    build:
      context: .
      dockerfile: ./dockerization/dockerfile.api
      args:
        PYTHON_VERSION: 3.9.20-alpine
    env_file: .env.production
    volumes:
      - media:/app/media
    networks:
      - net-gateway
      - net-pg
    depends_on:
      - pg

  pg:
    image: postgres:16
    container_name: file_storage_pg
    env_file: .env.production
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - net-pg
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready || exit 1" ]
