"""adds file model

Revision ID: 29eb78bb0c36
Revises: 2fc4fc7b716d
Create Date: 2024-09-08 13:07:36.215683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29eb78bb0c36'
down_revision: Union[str, None] = '2fc4fc7b716d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
