"""adds url to file model

Revision ID: ec4c3349c32e
Revises: 6ec9265471f5
Create Date: 2024-09-09 22:36:59.096802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec4c3349c32e'
down_revision: Union[str, None] = '6ec9265471f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'url')
    # ### end Alembic commands ###
