USERNAME_MIN_LENGTH = 1
USERNAME_MAX_LENGTH = 60
USERNAME_PATTERN = r'^[-a-zA-Z0-9_]+$'

PASSWORD_MIN_LENGTH = 6
PASSWORD_MAX_LENGTH = 100

FILE_NAME_MIN_LENGTH = 1
FILE_NAME_MAX_LENGTH = 100
FILE_PATH_MIN_LENGTH = 1
FILE_PATH_MAX_LENGTH = 1024

TAG_AUTH = 'Auth'
TAG_FILES = 'Files'
TAG_HEALTHCHECK = 'Healthcheck'

COOKIE_AUTH_PATH = 'Authorization'
SCOPE_AUTH_PATH = 'auth'
SCOPE_USER_PATH = 'user'

CHUNK_1MB = 1024 * 1024

URL_MEDIA_TOKEN_BYTES = 32

MEDIA_ROOT_NAME = 'media'
