USERNAME_MIN_LENGTH = 1
USERNAME_MAX_LENGTH = 60
USERNAME_PATTERN = r'^[-a-zA-Z0-9_]+$'

PASSWORD_MIN_LENGTH = 6
PASSWORD_MAX_LENGTH = 100

FILE_NAME_MIN_LENGTH = 1
FILE_NAME_MAX_LENGTH = 100
FILE_PATH_MIN_LENGTH = 1
FILE_PATH_MAX_LENGTH = 1024

TAG_AUTH = 'Auth'
TAG_FILES = 'Files'
TAG_HEALTHCHECK = 'Healthcheck'
