ARG PYTHON_VERSION=3.9.20

FROM python:${PYTHON_VERSION}

ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /app

RUN --mount=type=cache,target=/root/.cache/pip \
  --mount=type=bind,source=requirements.txt,target=requirements.txt \
  python3 -m pip install --upgrade pip && python3 -m pip install -r requirements.txt

COPY alembic.ini .

COPY requirements.txt .

COPY src src

EXPOSE 8000

CMD ["python3", "src/main.py"]
